#$schema: https://www.flowlauncher.com/schemas/settings-template.schema.json
body:
  - type: dropdown
    attributes:
      name: lang
      label: Language
      description: >-
        Choose your preferred language. Documentation pages on php.net will be
        opened in this language if available.
      defaultValue: English
      options:
        - English
        - German
        - Spanish
        - French
        - Italian
        - Japanese
        - Brazilian Portuguese
        - Russian
        - Turkish
        - Ukrainian
        - Chinese (Simplified)